version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - dev-network
    
  db:
    image: postgres:latest
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - dev-network
  

# not sure that the port configuration is correct for aws deployment
  # frontend-dev:
  #   build: 
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "80:80"
  #   stdin_open: true

volumes:
  postgres_data_dev:

networks:
  dev-network: