version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.nuc
    restart: always
    # volumes:
    #   - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    container_name: michaels-chalet-backend
    # networks:
    #   -app-network

  db:
    # build: ./database
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    # networks:
    #   - app-network
    container_name: michaels-chalet-db

volumes:
  postgres_data:


# networks:
#   app-network:


# not sure that the port configuration is correct for aws deployment
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: ./Dockerfile.nuc
  #   ports:
  #     - "80:80"
  #   stdin_open: true
