version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.prod
    ports:
      - "8000:8000"
    # normally this is just the run server command. Possibly change to a custom .sh script later on
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

# not sure that the port configuration is correct for aws deployment
  frontend-prod:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    ports:
      - "3000:80"
    stdin_open: true
