# Use an official Python runtime as a base image
# Difference between dev and nuc/prod is not overwritting settings.py w/ production_settings.py
FROM python:3.10-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /backend

# Install dependencies
COPY requirements.txt /backend/
RUN pip install --no-cache-dir -r requirements.txt

# Install Gunicorn
RUN pip install gunicorn

# Copy the current directory contents into the container
COPY . /backend/

# Migrate and make db - not sure this matters since it is also called in compose file
RUN python manage.py migrate

EXPOSE 8000

# Set entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]