# Generated by Django 5.0.1 on 2024-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=120, verbose_name='Created By')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('group_size', models.IntegerField(verbose_name='Group Size')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('request_message', models.TextField(verbose_name='Booking Message')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Booking Price')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Payment Received')),
                ('status', models.CharField(max_length=30, verbose_name='Booking Status')),
                ('admin_note', models.TextField(verbose_name='Admin Private Note')),
            ],
        ),
    ]
