# Generated by Django 5.0.1 on 2024-05-19 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaletsync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=120, verbose_name='Created By')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('group_size', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Group Size')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('request_message', models.TextField(verbose_name='Booking Message')),
                ('request_type', models.CharField(max_length=11, verbose_name='Request Type')),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='admin_note',
            field=models.TextField(default=None, null=True, verbose_name='Admin Private Note'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Booking Price'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='request_message',
            field=models.TextField(null=True, verbose_name='Booking Message'),
        ),
    ]
