# Generated by Django 5.0.1 on 2024-05-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaletsync', '0002_requests_alter_bookings_admin_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_message',
            field=models.TextField(null=True, verbose_name='Booking Message'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Request'), ('change', 'Change Request'), ('cancellation', 'Cancellation')], max_length=12, verbose_name='Request Type'),
        ),
    ]
