# Generated by Django 5.0.1 on 2024-05-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaletsync', '0007_requests_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='booking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chaletsync.bookings'),
        ),
    ]
